In [1]:
import pandas as pd
import pdal
import json
import geopandas as gpd
import numpy as np
import glob

In [3]:
gdf_articulacao = gpd.read_file("zip://data/SIRGAS_SHP_quadriculamdt.zip!/SIRGAS_SHP_quadriculamdt/")

In [4]:
gdf_articulacao.set_crs(epsg=31983, inplace=True)

qmdt_cod                                           geometry
0     3212-353  POLYGON ((329132.004 7367829.458, 329125.190 7...
1     3212-344  POLYGON ((328601.255 7367823.210, 328594.420 7...
2     3212-343  POLYGON ((328070.502 7367816.960, 328063.648 7...
3     3211-464  POLYGON ((327539.756 7367810.622, 327532.876 7...
4     3211-463  POLYGON ((327008.999 7367804.285, 327002.102 7...
...        ...                                                ...
5357  3234-241  POLYGON ((331960.582 7352864.137, 331967.325 7...
5358  3234-224  POLYGON ((333544.473 7353459.402, 333551.152 7...
5359  3336-444  POLYGON ((331725.429 7373051.662, 332256.363 7...
5360  3336-442  POLYGON ((331718.736 7373628.441, 332249.692 7...
5361  3336-414  POLYGON ((331712.043 7374205.219, 332243.020 7...

[5362 rows x 2 columns]

In [14]:
gdf_articulacao.loc[gdf_articulacao.qmdt_cod.str.startswith('2122'), 'qmdt_cod'].to_list()

4520    2122-223
4521    2122-214
4522    2122-221
4523    2122-212
4524    2122-231
4525    2122-222
4526    2122-232
Name: qmdt_cod, dtype: object

In [11]:
gdf_articulacao.qmdt_cod.sort_values().to_list()

['2122-212',
 '2122-214',
 '2122-221',
 '2122-222',
 '2122-223',
 '2122-231',
 '2122-232',
 '2222-132',
 '2222-163',
 '2222-164',
 '2222-211',
 '2222-212',
 '2222-214',
 '2222-221',
 '2222-222',
 '2222-223',
 '2222-224',
 '2222-231',
 '2222-232',
 '2222-233',
 '2222-234',
 '2222-242',
 '2222-243',
 '2222-244',
 '2222-251',
 '2222-252',
 '2222-253',
 '2222-254',
 '2222-261',
 '2222-262',
 '2222-263',
 '2222-264',
 '2222-322',
 '2222-324',
 '2222-331',
 '2222-332',
 '2222-333',
 '2222-334',
 '2222-352',
 '2222-354',
 '2222-361',
 '2222-362',
 '2222-363',
 '2222-364',
 '2222-411',
 '2222-412',
 '2222-413',
 '2222-414',
 '2222-421',
 '2222-422',
 '2222-423',
 '2222-424',
 '2222-431',
 '2222-432',
 '2222-433',
 '2222-434',
 '2222-441',
 '2222-442',
 '2222-443',
 '2222-444',
 '2222-451',
 '2222-452',
 '2222-453',
 '2222-454',
 '2222-461',
 '2222-462',
 '2222-463',
 '2222-464',
 '2224-122',
 '2224-123',
 '2224-124',
 '2224-131',
 '2224-132',
 '2224-133',
 '2224-134',
 '2224-142',
 '2224-144',

In [16]:
gdf_articulacao[~gdf_articulacao.qmdt_cod.isin(['3445-232'])]

qmdt_cod                                           geometry
0     3212-353  POLYGON ((329132.004 7367829.458, 329125.190 7...
1     3212-344  POLYGON ((328601.255 7367823.210, 328594.420 7...
2     3212-343  POLYGON ((328070.502 7367816.960, 328063.648 7...
3     3211-464  POLYGON ((327539.756 7367810.622, 327532.876 7...
4     3211-463  POLYGON ((327008.999 7367804.285, 327002.102 7...
...        ...                                                ...
5357  3234-241  POLYGON ((331960.582 7352864.137, 331967.325 7...
5358  3234-224  POLYGON ((333544.473 7353459.402, 333551.152 7...
5359  3336-444  POLYGON ((331725.429 7373051.662, 332256.363 7...
5360  3336-442  POLYGON ((331718.736 7373628.441, 332249.692 7...
5361  3336-414  POLYGON ((331712.043 7374205.219, 332243.020 7...

[5361 rows x 2 columns]

In [8]:
class Scm:

    def __init__(self, scm) -> None:
        
        coords = [[xy[0], xy[1]] for xy in gdf_articulacao.set_index('qmdt_cod').loc[scm].geometry.exterior.coords]
        xy_max = np.max(np.array(coords), axis=0) 
        xy_min = np.min(np.array(coords), axis=0)
        width, height = np.ceil(xy_max * 2) - np.ceil(xy_min * 2)

        origin_x, origin_y = np.floor(xy_min * 2)/2
        
        self.scm = scm
        self.width = width
        self.height = height
        self.origin_x = origin_x
        self.origin_y = origin_y


print(Scm('3315-361').origin_y)

7386800.0


In [4]:
gdf_articulacao.shape

(5362, 2)

In [8]:
DATA_DIR_2020 = '/media/fernando/DATA/LiDAR-Sampa-2020'
DATA_DIR_2017 = '/media/fernando/DATA/LiDAR-Sampa-2017'

In [32]:
glob.glob(f'{DATA_DIR_2017}/*.laz')

['/media/fernando/DATA/LiDAR-Sampa-2017/MDS_color_3443-442.laz',
 '/media/fernando/DATA/LiDAR-Sampa-2017/MDS_color_3324-354.laz',
 '/media/fernando/DATA/LiDAR-Sampa-2017/MDS_color_3333-213.laz',
 '/media/fernando/DATA/LiDAR-Sampa-2017/MDS_color_3316-362.laz',
 '/media/fernando/DATA/LiDAR-Sampa-2017/MDS_color_3335-243.laz',
 '/media/fernando/DATA/LiDAR-Sampa-2017/MDS_color_2446-123.laz',
 '/media/fernando/DATA/LiDAR-Sampa-2017/MDS_color_3322-161.laz',
 '/media/fernando/DATA/LiDAR-Sampa-2017/MDS_color_2244-264.laz',
 '/media/fernando/DATA/LiDAR-Sampa-2017/MDS_color_3433-323.laz',
 '/media/fernando/DATA/LiDAR-Sampa-2017/MDS_color_4311-353.laz',
 '/media/fernando/DATA/LiDAR-Sampa-2017/MDS_color_3241-344.laz',
 '/media/fernando/DATA/LiDAR-Sampa-2017/MDS_color_2342-352.laz',
 '/media/fernando/DATA/LiDAR-Sampa-2017/MDS_color_3236-134.laz',
 '/media/fernando/DATA/LiDAR-Sampa-2017/MDS_color_3314-424.laz',
 '/media/fernando/DATA/LiDAR-Sampa-2017/MDS_color_3443-232.laz',
 '/media/fernando/DATA/Li

In [12]:
len(glob.glob(f'{DATA_DIR_2020}/*.laz')), len(glob.glob(f'{DATA_DIR_2017}/*.laz'))

(5390, 5362)

In [27]:
scms_fora_art = np.isin(
    np.unique(np.array([file.split('_')[-2] for file in glob.glob(f'{DATA_DIR_2020}/*.laz')])),
    gdf_articulacao.qmdt_cod.to_numpy()
)

In [29]:
np.unique(np.array([file.split('_')[-2] for file in glob.glob(f'{DATA_DIR_2020}/*.laz')]))[~scms_fora_art]

array(['2122-224', '2222-213', '2226-413', '2226-441', '2226-443',
       '2242-143', '2242-311', '2244-311', '2324-222', '2324-352',
       '2326-254', '2326-424', '2344-144', '2442-242', '2442-331',
       '2443-222', '2446-454', '3216-264', '3235-353', '3235-461',
       '3236-361', '3325-434', '3336-412', '3341-251', '3341-253',
       '3341-361', '3341-413', '3426-313', '3426-331', '3426-362',
       '3434-224', '3441-134', '3441-321', '3441-342', '3441-344'],
      dtype='<U8')

In [6]:
gdf_articulacao.set_index('qmdt_cod').loc['3315-361']

geometry    POLYGON ((323593.445 7386800.007, 323586.469 7...
Name: 3315-361, dtype: geometry

In [7]:
#gdf_articulacao.set_index('qmdt_cod').iloc[3315-361].geometry.exterior.coords
coords = [[xy[0], xy[1]] for xy in gdf_articulacao.set_index('qmdt_cod').loc['3315-361'].geometry.exterior.coords]
xy_max = np.max(np.array(coords), axis=0) 
xy_min = np.min(np.array(coords), axis=0)

In [8]:
np.array(coords)

array([[ 323593.445, 7386800.007],
       [ 323586.469, 7387376.793],
       [ 324117.945, 7387383.21 ],
       [ 324124.9  , 7386806.425],
       [ 323593.445, 7386800.007]])

In [9]:
np.ceil(xy_max * 2) - np.ceil(xy_min * 2)

array([1077., 1166.])

In [10]:
xy_min, xy_max

(array([ 323586.469, 7386800.007]), array([ 324124.9 , 7387383.21]))

In [11]:
np.floor(xy_min * 2)/2

array([ 323586., 7386800.])

In [20]:
## GERA MDS e MDT

laz = [
    {
        "type":"readers.las",
        "filename":"sample-data/MDS_3315-361_1000.laz"
    },
    {
        "filename":"sample-result/MDS-3315-361.tiff",
        "gdaldriver":"GTiff",
        "output_type":"max",
        "resolution":"0.5",
        "type": "writers.gdal",
        "gdalopts":"COMPRESS=ZSTD, PREDICTOR=3, BIGTIFF=YES",
    },
    {
        "type": "filters.delaunay",
        "where": "(Classification == 2)"
    },
    {
        "type": "filters.faceraster",
        "resolution": 0.5,
        "width": 1077,
        "height": 1166,
        "origin_x": 323586,
        "origin_y": 7386800
    },
    {
        "filename":"sample-result/MDT-3315-361.tiff",
        "type": "writers.raster",
        # "filename":f"results/DTM-{grid_number}.tiff",
        "gdaldriver":"GTiff",
        "data_type": "float32",
        "gdalopts":"COMPRESS=ZSTD, PREDICTOR=3, BIGTIFF=YES",
    }, 
]

In [21]:
pipeline = pdal.Pipeline(json.dumps(laz))
n_points = pipeline.execute()
print(f'Pipeline selected {n_points} points')

Pipeline selected 5365968 points
